### ISSUE TITLE
Login: Storing sessions

### ISSUE THREAD

**Issue by ralfz123** [RowinRuizendaal/Bloom#14]

**Comment by RowinRuizendaal** [comment]
https://github.com/RowinRuizendaal/Bloom/pull/40

Authorization routes now working with temp vuex store state

**Comment by RowinRuizendaal** [comment]
https://github.com/RowinRuizendaal/Bloom/pull/48

**Comment by RowinRuizendaal** [comment]
Merge has been accepted, and is currently living on the master branch
