### ISSUE TITLE
Try a more modular approach here

### ISSUE THREAD

**Issue by TuriGuilano** [RowinRuizendaal/Bloom#23]
https://github.com/RowinRuizendaal/Bloom/blob/0923374b8e9ba1089ca55b85d89886d21d56438a/server/server.js#L16-L27

Maybe it's an idea to create a config folder where you can write your db logic - then export the connect function and simply call that function inside your index.js / app.js. This way you keep your root file clean.

**Comment by ralfz123** [comment]
Thanks Janno! I've almost done that!
