### ISSUE TITLE
Adding additional logic to schema

### ISSUE THREAD

**Issue by TuriGuilano** [RowinRuizendaal/Bloom#26]
https://github.com/RowinRuizendaal/Bloom/blob/0923374b8e9ba1089ca55b85d89886d21d56438a/server/app/models/user.js#L5-L16

You can write more in depth requirements for your schema, e.g:

```js
email: {     
  type: String,      
  required: [true, 'E-mail is verplicht'],      
  unique: true,      
  trim: true,      
  minlength: 1,      
  maxlength: [50, 'E-mail mag niet meer karakters dan 50 bevatten']    
}
```

**Comment by RowinRuizendaal** [comment]
Thank you for the feedback @TuriGuilano
