### ISSUE TITLE
Can this file be removed?

### ISSUE THREAD

**Issue by ju5tu5** [RowinRuizendaal/Bloom#56]
https://github.com/RowinRuizendaal/Bloom/blob/0c2ec3632007e36f73d91273afd30e8272b05d03/server/app/models/tutorial.model.js#L1

**Comment by RowinRuizendaal** [comment]
Yes, thank you for the reminder, we need to remove this file :)

**Comment by RowinRuizendaal** [comment]
@ralfz123 , can you delete this file in your branch?

**Comment by ralfz123** [comment]
> @ralfz123 , can you delete this file in your branch?

Yes I will :fire: 

[Done 👍 ](https://github.com/RowinRuizendaal/Bloom/commit/e48da6474ea43c7a8882aa8e17728a91b51252b3)
