### ISSUE TITLE
li elements need to be nested inside ul/ol

### ISSUE THREAD

**Issue by ju5tu5** [RowinRuizendaal/Bloom#57]
https://github.com/RowinRuizendaal/Bloom/blob/0c2ec3632007e36f73d91273afd30e8272b05d03/client/src/views/onboarding.vue#L5

**Comment by RowinRuizendaal** [comment]
Thanks for your review, we are going to refactor this in the last week of the project

**Comment by RowinRuizendaal** [comment]
Done
