### ISSUE TITLE
Button step 10 needs to be aligned right instead of left

### ISSUE THREAD

**Issue by RowinRuizendaal** [RowinRuizendaal/Bloom#64]

**Comment by ralfz123** [comment]
## First

![Screenshot 2021-06-14 at 10 28 13](https://user-images.githubusercontent.com/55750121/121862587-3ac86000-ccfb-11eb-839e-73126f380d82.png)

**Comment by ralfz123** [comment]
## Later

![Screenshot 2021-06-14 at 10 57 23](https://user-images.githubusercontent.com/55750121/121866534-4e75c580-ccff-11eb-8bab-60bec56447c9.png)
