### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by RowinRuizendaal** [RowinRuizendaal/Bloom#67]
Update the readme and check the grammar

**Comment by ralfz123** [comment]
## To-do's
- [ ] functions/methods/folderstructure
- [ ] PWA: gif + explanation + files
- [ ] Vuex store 
- [ ] encryping
- [ ] password hashing
- [x] UI screenshots

**Comment by ralfz123** [comment]
### Added features and User Interface screenshots
[link README](https://github.com/RowinRuizendaal/Bloom/blob/60a413a642b7afd1aa969bf88d4312e5817d3050/README.md)
[link commit](https://github.com/RowinRuizendaal/Bloom/commit/60a413a642b7afd1aa969bf88d4312e5817d3050)
